version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stemed
      MYSQL_USER: stemed
      MYSQL_PASSWORD: stemed
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://stemed:stemed@db:3306/stemed
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  db_data:
